spring:
  cloud:
    gateway:
      globalcors:
        
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE